version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    environment:
      - "TZ=Japan"
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - db
    tty: true

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./flask:/app
    ports:
      - 5000:5000
    links:
      - db
    tty: true

  db:
    build:
      context: .
      dockerfile: ./docker/rdb/Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: flask
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      # - ./docker/rds/data:/var/lib/mysql
      - ./docker/rds/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/rds/sql:/docker-entrypoint-initdb.d
      - ./docker/rds/log:/var/log/mysql
    ports:
      - 3306:3306
